schemaVersion: 2.2.0
metadata:
  description: A template for setting up a Django-MySQL application
  name: template
  version: 0.0.1
components:
  - name: mysqlimage
    image:
      autoBuild: true
      dockerfile:
        buildContext: .
        rootRequired: false
        uri: Containerfile-db
      imageName: mysqlimage
  - name: mysql
    container:
      image: mysqlimage
      endpoints:
      - name: http-3306
        targetPort: 3306
      env:
      - name: MYSQL_HOST
        value: localhost
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: mydatabase
      - name: MYSQL_USER
        value: myuser
      - name: MYSQL_PASSWORD
        value: mypassword
    attributes:
      container-overrides:
        imagePullPolicy: Never
  - name: webimage
    image:
      autoBuild: true
      dockerfile:
        buildContext: .
        rootRequired: false
        uri: Containerfile-web
      imageName: webimage
  - name: web
    container:
      image: webimage
      command: ['/bin/sh']
      args:
      - -c
      - 'until python3 -c "import socket; exit(0) if 0 == socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect_ex((''127.0.0.1'',3306)) else exit(1)"; do echo Waiting for DB; sleep 2; done && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
      endpoints:
      - name: http-8000
        targetPort: 8000
    attributes:
      container-overrides:
        imagePullPolicy: Never
