# Pull official base image

## Mac/Windows/Linux x86
FROM python:3.12

## Mac M-Series
## FROM arm64v8/python:3.12

# Set environment variables
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# Install dependencies
WORKDIR /app
RUN pip install --upgrade pip
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# Create a user with UID 1000 and GID 1000
RUN groupapp -g 1000 appgroup && \
    user add -r -u 1000 -g appgroup appuser

# Switch to this user
USER 1000:1000

# Copy project
COPY ./template /app/

RUN python3 manage.py makemigrations polls

CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

