# Pull official base image

## Mac/Windows/Linux x86
FROM python:3.12

## Mac M-Series
## FROM arm64v8/python:3.12

# Set environment variables
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# apt-get update + vim install for editing
RUN yes | apt-get update && yes | apt-get upgrade
RUN yes | apt-get install vim

# Install dependencies
WORKDIR /app
RUN pip install --upgrade pip
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# Copy project
COPY ./template /app/

RUN python3 manage.py makemigrations polls

# Copy wait-for-it
COPY wait-for-it.sh wait-for-it.sh
RUN chmod +x wait-for-it.sh

CMD ["./wait-for-it.sh", "localhost:3306", "--timeout=20", "--", "sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

