# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.8.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-03-01T14:53:39Z"
  labels:
    app: helloworld
  name: helloworld
spec:
  containers:
  - image: docker.io/library/podman-django-template-web:latest
    name: web
    ports:
    - containerPort: 8000
      hostPort: 8000
  - args:
    - mysqld
    image: docker.io/library/podman-django-template-db:latest
    name: db
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: b8a75e565feaec19b27076f8b1b30d140b401bc1f18437ea66438a16a34b64b5-pvc
  volumes:
  - name: b8a75e565feaec19b27076f8b1b30d140b401bc1f18437ea66438a16a34b64b5-pvc
    persistentVolumeClaim:
      claimName: b8a75e565feaec19b27076f8b1b30d140b401bc1f18437ea66438a16a34b64b5

