version: '3'
services:
  mysql: 
    build:
      dockerfile: Containerfile-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: helloworld
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql

  web:
    build:
      dockerfile: Containerfile-web
    ports:
      - "8004:8000"
    depends_on:
      - mysql
