version: '3'
services:
  mysql: 
    build:
      dockerfile: Containerfile-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:3306"]
      interval: 10s
      timeout: 10s
      retries: 5

  web:
    build:
      dockerfile: Containerfile-web
    ports:
      - "8004:8000"
    depends_on:
      mysql:
        condition: service_healthy
