version: '22'
services:
  template-db: 
    build:
      dockerfile: Containerfile-db
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:3306"]
      interval: 30s
      timeout: 40s
      retries: 5

  template-web:
    build:
      dockerfile: Containerfile-web
    ports:
      - "8004:8000"
    depends_on:
      template-db:
        condition: service_healthy
