apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f podman-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
    - name: "8004"
      port: 8004
      targetPort: 8000
  selector:
    io.kompose.service: web
