apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f podman-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f podman-compose.yml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/podman-django-template-default: "true"
        io.kompose.service: web
    spec:
      containers:
        - image: web
          name: web
          ports:
            - containerPort: 8000
              hostPort: 8004
              protocol: TCP
      restartPolicy: Always
